[package]
name = "hog4midictrl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
midir = {version="0.9.1", features=["winrt"]}
midly = "0.5.3"
rosc = "0.10.1"
